config/routes.rb
Rails.application.routes.draw do
  resources :news_releases

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :contacts

  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :phones, dependent: :destroy, inverse_of: :contact
  accepts_nested_attributes_for :phones

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phones, length: { is: 3 }

  def name
    [firstname, lastname].join(' ')
  end

  def self.by_letter(letter)
    where("lastname LIKE ?", "#{letter}%").order(:lastname)
  end
end

app/models/news_release.rb
class NewsRelease < ApplicationRecord
  validates :released_on, presence: true
  validates :title, presence: true
  validates :body, presence: true

  def title_with_date
    "#{released_on.strftime('%Y-%m-%d')}: #{title}"
  end
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact, inverse_of: :phones

  validates :phone, uniqueness: { scope: :contact_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    redirect_to login_url, alert: 'Please log in first' if current_user.nil?
  end

  def can_administer?
    redirect_to root_url, alert: 'Access denied.' unless administrator?
  end

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def administrator?
      current_user && current_user.admin?
    end

    helper_method :administrator?
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts =
      if params[:letter]
        Contact.by_letter(params[:letter])
      else
        Contact.order('lastname, firstname')
      end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new

    %w(home office mobile).each do |phone|
      @contact.phones.build(phone_type: phone)
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.fetch(:contact, {}).permit(:firstname, :lastname, :email,
        phones_attributes: [:id, :phone, :phone_type])
    end
end

app/controllers/news_releases_controller.rb
class NewsReleasesController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :set_news_release, only: [:show, :edit, :update, :destroy]

  # GET /news_releases
  # GET /news_releases.json
  def index
    @news_releases = NewsRelease.all
  end

  # GET /news_releases/1
  # GET /news_releases/1.json
  def show
  end

  # GET /news_releases/new
  def new
    @news_release = NewsRelease.new
  end

  # GET /news_releases/1/edit
  def edit
  end

  # POST /news_releases
  # POST /news_releases.json
  def create
    @news_release = NewsRelease.new(news_release_params)

    respond_to do |format|
      if @news_release.save
        format.html { redirect_to news_releases_url, notice: 'Successfully created news release.' }
        format.json { render :show, status: :created, location: @news_release }
      else
        format.html { render :new }
        format.json { render json: @news_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_releases/1
  # PATCH/PUT /news_releases/1.json
  def update
    respond_to do |format|
      if @news_release.update(news_release_params)
        format.html { redirect_to @news_release, notice: 'News release was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_release }
      else
        format.html { render :edit }
        format.json { render json: @news_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_releases/1
  # DELETE /news_releases/1.json
  def destroy
    @news_release.destroy
    respond_to do |format|
      format.html { redirect_to news_releases_url, notice: 'News release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_release
      @news_release = NewsRelease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_release_params
      params.fetch(:news_release, {}).permit(:title, :released_on, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :can_administer?, except: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: 'New user created.'
    else
      render :new
    end
  end

  private

    def user_params
      params[:user].delete :admin unless current_user.try(:admin?)
      params.fetch(:user, {}).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/news_releases_helper.rb
module NewsReleasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    div id="error_explanation"
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  div class="form-inputs"
    div class="form-group"
      = f.label :firstname
      br
      = f.text_field :firstname
    div class="form-group"
      = f.label :lastname
      br
      = f.text_field :lastname
    div class="form-group"
      = f.label :email
      br
      = f.text_field :email
    = f.fields_for :phones do |builder|
      div class="form-group"
        = builder.hidden_field :phone_type
        = builder.label :phone, "#{builder.object.phone_type.capitalize} phone"
        br
        = builder.text_field :phone
  div class="form-actions" = f.submit nil, class: 'btn btn-primary'

app/views/contacts/edit.html.slim
h1 Editing contact

== render 'form'

app/views/contacts/index.html.slim
h1 Contacts

- if @contacts.empty?
  p No contacts found.
- else
  table class="table table-striped table-hover"
    thead
      tr
        th Name
        th Email
        - if current_user
          th

    tbody
      - @contacts.each do |contact|
        tr
          td = link_to contact.name, contact
          td = contact.email
          - if current_user
            td style="text-align:right;"
              = link_to 'Edit', edit_contact_path(contact), class: 'btn btn-default btn-xs'
              =< link_to 'Destroy', contact, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-xs'

- if current_user
  div class="form-actions"
    = link_to 'New Contact', new_contact_path, class: 'btn btn-primary'

app/views/contacts/new.html.slim
h1 New contact

== render 'form'

app/views/contacts/show.html.slim
h1 = @contact.name

p = @contact.email

- unless @contact.phones.empty?
  h2 Phones
  
  ul
    - @contact.phones.each do |phone|
      li
        = phone.phone_type
        = phone.phone

- if current_user
  div class="form-actions"
    = link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title BigCo Company Directory
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    /[if lt IE 9]
      script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
      script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
  body
    div class="navbar navbar-default navbar-fixed-top" role="navigation"
      div class="container"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="#" BigCo, Inc.
        div class="navbar-collapse collapse"
          ul class="nav navbar-nav"
            li = link_to "Home", root_path
            li = link_to "About Us", '#about_us', data: {toggle: 'modal', target: '#about_us' }
            li = link_to "News", news_releases_path
            li = link_to "Contact Us", '#'
          ul class="nav navbar-nav navbar-right"
            - if current_user
              - if administrator?
                li = link_to 'Users', users_path
              li = link_to 'Log Out', logout_path
            - else
              li = link_to 'Log In', new_session_path

    div class="container"
      div class="btn-group btn-group-justified"
        - ('A'..'Z').each do |letter|
          = link_to letter, contacts_path(letter: letter), class: 'btn btn-default'
        = link_to 'All', contacts_path, class: 'btn btn-default'

      - flash.each do |name, msg|
        div class="alert alert-#{name == 'notice' ? 'success' : 'error'}"
          button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
          = msg

      == yield

    div class="modal fade" id="about_us"
      div class="modal-dialog"
        div class="modal-content"
          div class="modal-header"
            button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
            h4 class="modal-title" About BigCo, Inc.
          div class="modal-body"
            p BigCo produces the finest widgets in all the land.
          div class="modal-footer"
            button type="button" class="btn btn-default" data-dismiss="modal" Close

app/views/news_releases/_form.html.slim
= form_for(@news_release) do |f|
  - if @news_release.errors.any?
    div id="error_explanation"
      h2 #{pluralize(@news_release.errors.count, "error")} prohibited this news_release from being saved:

      ul
        - @news_release.errors.full_messages.each do |message|
          li = message

  div class="field"
    = f.label :title
    br
    = f.text_field :title
  div class="field"
    = f.label :released_on, 'Date'
    br
    = f.text_field :released_on
  div class="field"
    = f.label :body
    br
    = f.text_area :body
  div class="actions"
    = f.submit

app/views/news_releases/edit.html.slim
h1 Editing news_release

== render 'form'

= link_to 'Show', @news_release
'|
= link_to 'Back', news_releases_path

app/views/news_releases/index.html.slim
h1 News releases

ul
  - @news_releases.each do |news_release|
    li = link_to news_release.title_with_date, news_release

- if current_user
  = link_to 'Add News Release', new_news_release_path, class: 'btn btn-primary'

app/views/news_releases/new.html.slim
h1 New news_release

== render 'form'

= link_to 'Back', news_releases_path

app/views/news_releases/show.html.slim
p id="notice" = notice

p
  strong Title:
  = @news_release.title

p
  strong Released on:
  = @news_release.released_on

p
  strong Body:
  = @news_release.body

= link_to 'Edit', edit_news_release_path(@news_release)
'|
= link_to 'Back', news_releases_path

app/views/users/index.html.slim
h1 Users

table class="table table-striped table-hover"
  tr
    th Email
    th Admin?
  - @users.each do |user|
    tr
      td = user.email
      td = user.admin?

- if administrator?
  div class="form-actions"
    = link_to 'New User', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
h1 New User

= form_for @user do |f|
  - if @user.errors.any?
    div class="error_messages"
      h2 Form is invalid
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  div class="form-inputs"
    div class="form-group"
      = f.label :email
      br
      = f.text_field :email
    div class="form-group" id="password"
      = f.label :password
      br
      = f.password_field :password
    div class="form-group" id="password_confirmation"
      = f.label :password_confirmation
      br
      = f.password_field :password_confirmation
    div class="form-group"
      = f.label :admin do
        => f.check_box :admin
        | Administrator?
      end

  div class="form-actions"
    = f.submit 'Create User', class: 'btn btn-primary'